### ISSUE TITLE
Alignment of GitHub stats

### ISSUE THREAD

**Issue by avneesh0612** [krishguptadev/krishguptadev#10]
The stats are not aligned well-
![image](https://user-images.githubusercontent.com/76690419/143998074-5b7364c6-bd54-4344-bfdf-737ef383bf1d.png)

**Comment by krishguptadev** [comment]
Dunno a better way? Shall I add a hr in b/w

**Comment by krishguptadev** [comment]
This is good? 
![image](https://user-images.githubusercontent.com/91655303/143998576-a0f33a6f-6595-4e0a-b017-db52a4210519.png)

**Comment by avneesh0612** [comment]
Ah yes

**Comment by avneesh0612** [comment]
I was making a PR for the same 🤦‍♂️

**Comment by avneesh0612** [comment]
![image](https://user-images.githubusercontent.com/76690419/143998894-b602f2b5-fa56-418e-858a-8629ed96c1c3.png)
I think the PR is still needed 😂

**Comment by krishguptadev** [comment]
oh crap 😂

**Comment by avneesh0612** [comment]
😂
